const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const SRC_RI = path.join(ROOT, 'ri');
const DIST = path.join(ROOT, 'dist');
const DIST_RI = path.join(DIST, 'ri');
const CONFIG_FILE = path.join(ROOT, 'config.json');

// Helper: Shuffle Array (Fisher-Yates)
function shuffle(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}

// Main function
function build() {
    console.log('Starting build...');

    // Load Config
    let config = { domain: '' };
    
    // Priority 1: Environment Variable
    if (process.env.DOMAIN) {
        config.domain = process.env.DOMAIN;
        console.log('Loaded domain from environment variable.');
    } 
    // Priority 2: Config File
    else if (fs.existsSync(CONFIG_FILE)) {
        try {
            const configContent = fs.readFileSync(CONFIG_FILE, 'utf8');
            const parsed = JSON.parse(configContent);
            if (parsed.domain) {
                config.domain = parsed.domain;
            }
            console.log('Loaded domain from config.json.');
        } catch (e) {
            console.warn('Failed to parse config.json, using default settings.');
        }
    }

    // Normalize domain (remove trailing slash)
    if (config.domain) {
        config.domain = config.domain.replace(/\/$/, '');
    }

    console.log(`Using domain prefix: "${config.domain}"`);

    // 1. Clean/Create Dist
    if (fs.existsSync(DIST)) {
        fs.rmSync(DIST, { recursive: true, force: true });
    }
    fs.mkdirSync(DIST, { recursive: true });
    fs.mkdirSync(DIST_RI, { recursive: true });

    // 2. Process Folders
    const types = ['h', 'v'];
    let counts = {};
    
    types.forEach(type => {
        const srcFolder = path.join(SRC_RI, type);
        const distFolder = path.join(DIST_RI, type);
        
        if (!fs.existsSync(srcFolder)) {
            console.warn(`Source folder not found: ${srcFolder}`);
            counts[type] = 0;
            return;
        }

        fs.mkdirSync(distFolder, { recursive: true });

        // Read and Filter Images
        let files = fs.readdirSync(srcFolder).filter(f => f.match(/\.(webp|jpg|jpeg|png|gif)$/i));
        
        // Shuffle
        files = shuffle(files);

        // Copy and Rename
        files.forEach((file, index) => {
            const srcPath = path.join(srcFolder, file);
            // User requested 1.webp, 2.webp, etc.
            const destPath = path.join(distFolder, `${index + 1}.webp`);
            fs.copyFileSync(srcPath, destPath);
        });

        counts[type] = files.length;
        console.log(`Processed ${type}: ${counts[type]} images.`);
    });

    // 3. Generate Single JS
    const jsContent = `
/**
 * Static Random Pic API
 * Generated by build script
 */
(function() {
    var counts = ${JSON.stringify(counts)};
    var domain = '${config.domain}';
    
    // State management for session consistency
    var sessionRandomH = null;
    var sessionRandomV = null;

    // Helper: Get random URL for a type (h or v), persistent per session
    function getRandomUrl(type) {
        if (!counts[type] || counts[type] === 0) return '';
        
        // Return existing session URL if available
        if (type === 'h' && sessionRandomH) return sessionRandomH;
        if (type === 'v' && sessionRandomV) return sessionRandomV;

        // Generate new if not exists
        var num = Math.floor(Math.random() * counts[type]) + 1;
        var url = domain + '/ri/' + type + '/' + num + '.webp';

        // Save to session state
        if (type === 'h') sessionRandomH = url;
        if (type === 'v') sessionRandomV = url;

        return url;
    }

    // Expose global functions
    window.getRandomPicH = function() { return getRandomUrl('h'); };
    window.getRandomPicV = function() { return getRandomUrl('v'); };

    // 1. Logic for Background (Customized based on user request)
    function setRandomBackground() { 
         // Get random URL using the helper (Dynamic count & domain)
         const bgUrl = getRandomUrl('h');
          
         // Find the background box element 
         const bgBox = document.getElementById('bg-box'); 
          
         if (bgBox) { 
             // Preload image 
             const img = new Image(); 
             img.onload = function() { 
                 bgBox.style.backgroundImage = \`url('\${bgUrl}')\`; 
                 bgBox.classList.add('loaded'); 
                 console.log('Random background loaded:', bgUrl); 
                  
                 // Set CSS variables for transparency effects 
                 document.documentElement.style.setProperty('--card-bg', 'var(--card-bg-transparent)'); 
                 document.documentElement.style.setProperty('--float-panel-bg', 'var(--float-panel-bg-transparent)'); 
             }; 
             img.onerror = function() { 
                 console.error('Failed to load background image:', bgUrl); 
             }; 
             img.src = bgUrl; 
         } else { 
             // Fallback: If no #bg-box, check for data-random-bg for backward compatibility/other elements
             // This keeps the generic functionality available if needed, but prioritizes the user's specific logic above.
             initGenericBackgrounds();
         } 
    }

    // 2. Logic for Image Tags (Generic)
    function initImgTags() {
        var imgTags = document.getElementsByTagName('img');
        for (var i = 0; i < imgTags.length; i++) {
            var img = imgTags[i];
            var alt = img.getAttribute('alt');
            var src = img.getAttribute('src');

            if (alt === 'random:h' || (src && src.indexOf('/random/h') !== -1)) {
                img.src = getRandomUrl('h');
            } else if (alt === 'random:v' || (src && src.indexOf('/random/v') !== -1)) {
                img.src = getRandomUrl('v');
            }
        }
    }

    // Helper for generic data-random-bg (as a backup or secondary feature)
    function initGenericBackgrounds() {
        var bgElements = document.querySelectorAll('[data-random-bg]');
        bgElements.forEach(function(el) {
            // Skip if it is the bg-box we already handled (though setRandomBackground handles #bg-box specifically)
            if (el.id === 'bg-box') return;

            var type = el.getAttribute('data-random-bg');
            if (type === 'h' || type === 'v') {
                var url = getRandomUrl(type);
                if (url) {
                    var img = new Image();
                    img.onload = function() {
                        el.style.backgroundImage = 'url("' + url + '")';
                        el.classList.add('loaded');
                    };
                    img.src = url;
                }
            }
        });
    }

    function init() {
        setRandomBackground();
        initImgTags();
    }
  
    // Run on initial load 
    if (document.readyState === 'loading') { 
        document.addEventListener('DOMContentLoaded', init); 
    } else { 
        init(); 
    } 
  
    // Swup integration
    function setupSwup() {
        if (window.swup && window.swup.hooks) {
            // Register hook for content replacement
            window.swup.hooks.on('content:replace', init);
            console.log('Random Pic API: Registered with Swup hooks.');
        }
    }

    if (window.swup) {
        setupSwup();
    } else {
        document.addEventListener('swup:enable', setupSwup);
    }

    // Legacy Swup support
    document.addEventListener('swup:contentReplaced', init); 
})();
`;
    fs.writeFileSync(path.join(DIST, 'random.js'), jsContent.trim());

    // Copy index.html if exists and not empty
    const indexSrc = path.join(ROOT, 'index.html');
    if (fs.existsSync(indexSrc)) {
         const stats = fs.statSync(indexSrc);
         if (stats.size > 0) {
             fs.copyFileSync(indexSrc, path.join(DIST, 'index.html'));
             console.log('Copied index.html to dist');
         } else {
             console.log('index.html is empty, creating a demo page in dist...');
             createDemoHtml();
         }
    } else {
        createDemoHtml();
    }

    // 4. Generate Gallery Page
    createGalleryHtml(counts, config);
    
    console.log('Build complete. Output is in /dist folder.');
}

function createGalleryHtml(counts, config) {
    const domain = config.domain;
    const types = Object.keys(counts);

    // 1. Prepare Libs in dist/lib
    const libDir = path.join(DIST, 'lib');
    fs.mkdirSync(libDir, { recursive: true });
    
    try {
        // Try to copy from node_modules if they exist
        const masonrySrc = path.join(ROOT, 'node_modules', 'masonry-layout', 'dist', 'masonry.pkgd.min.js');
        const imagesLoadedSrc = path.join(ROOT, 'node_modules', 'imagesloaded', 'imagesloaded.pkgd.min.js');
        const lozadSrc = path.join(ROOT, 'node_modules', 'lozad', 'dist', 'lozad.min.js');
        
        if (fs.existsSync(masonrySrc)) fs.copyFileSync(masonrySrc, path.join(libDir, 'masonry.pkgd.min.js'));
        if (fs.existsSync(imagesLoadedSrc)) fs.copyFileSync(imagesLoadedSrc, path.join(libDir, 'imagesloaded.pkgd.min.js'));
        if (fs.existsSync(lozadSrc)) fs.copyFileSync(lozadSrc, path.join(libDir, 'lozad.min.js'));
    } catch (e) {
        console.warn('Could not copy libraries. Ensure npm install is run.', e);
    }

    let galleryContent = '';

    // 2. Generate Sections per Type
    let navButtons = `<button class="filter-btn active" onclick="filterGallery('all')">All</button>`;
    
    types.forEach(type => {
        const count = counts[type];
        if (count === 0) return;

        navButtons += `<button class="filter-btn" onclick="filterGallery('${type}')">${type.toUpperCase()}</button>`;

        let itemsHtml = '';
        for (let i = 1; i <= count; i++) {
             const url = domain ? `${domain}/ri/${type}/${i}.webp` : `./ri/${type}/${i}.webp`;
             // Use data-src for lozad, add class 'lozad'
             itemsHtml += `<div class="grid-item"><img class="lozad" data-src="${url}" alt="${type}-${i}"></div>\n`;
        }

        galleryContent += `
        <section id="section-${type}" class="gallery-section">
            <h2>Folder: ${type}</h2>
            <div class="grid" id="grid-${type}">
                <div class="grid-sizer"></div>
                ${itemsHtml}
            </div>
        </section>
        `;
    });

    const htmlContent = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gallery - Static Random Pic API</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f0f2f5;
        }
        h1 { text-align: center; color: #333; margin-bottom: 20px; }
        
        /* Filter Nav */
        .filter-nav { text-align: center; margin-bottom: 30px; }
        .filter-btn {
            background: #fff; border: 1px solid #ddd; padding: 8px 16px; margin: 0 5px;
            border-radius: 20px; cursor: pointer; transition: all 0.2s; font-size: 14px;
            color: #555;
        }
        .filter-btn:hover { background: #f8f9fa; border-color: #ccc; }
        .filter-btn.active { background: #007bff; color: white; border-color: #007bff; }

        h2 { border-bottom: 2px solid #ddd; padding-bottom: 10px; margin-top: 40px; color: #555; text-transform: uppercase; font-size: 1.2rem; }
        
        /* Masonry Grid */
        .grid {
            margin: 0 auto;
        }
        .grid-sizer, .grid-item {
            width: 23%; /* 4 columns by default */
            margin-bottom: 10px;
        }
        .grid-item {
            float: left;
            background: #fff;
            border-radius: 4px;
            overflow: hidden;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
            min-height: 150px; /* Initial loading height */
            background-color: #eee;
            transition: background-color 0.3s;
        }
        /* When loaded, remove min-height constraint so it fits content exactly */
        .grid-item.content-loaded {
            min-height: 0;
            background-color: #fff;
        }
        
        .grid-item img {
            display: block;
            width: 100%;
            height: auto;
            opacity: 0;
            transition: opacity 0.4s;
        }
        /* Fade in when loaded */
        .grid-item img[data-loaded="true"] {
            opacity: 1;
        }

        /* Responsive */
        @media (max-width: 1200px) {
            .grid-sizer, .grid-item { width: 31%; }
        }
        @media (max-width: 800px) {
            .grid-sizer, .grid-item { width: 48%; }
        }
        @media (max-width: 500px) {
            .grid-sizer, .grid-item { width: 100%; }
        }
    </style>
</head>
<body>
    <h1>Static Image Gallery</h1>
    
    <div class="filter-nav">
        ${navButtons}
    </div>

    ${galleryContent}

    <!-- Libs -->
    <script src="lib/masonry.pkgd.min.js"></script>
    <script src="lib/imagesloaded.pkgd.min.js"></script>
    <script src="lib/lozad.min.js"></script>
    <script>
        var masonryInstances = [];

        document.addEventListener('DOMContentLoaded', function() {
            var grids = document.querySelectorAll('.grid');
            
            // Initialize Masonry first
            grids.forEach(function(grid) {
                var msnry = new Masonry(grid, {
                    itemSelector: '.grid-item',
                    columnWidth: '.grid-sizer',
                    percentPosition: true,
                    gutter: 15
                });
                masonryInstances.push(msnry);
            });

            // Initialize Lozad (Lazy Loading)
            const observer = lozad('.lozad', {
                rootMargin: '200px 0px', // Start loading earlier
                threshold: 0, // Trigger immediately when even 1px is visible (or within margin)
                loaded: function(el) {
                    // Function to handle load complete
                    const onImgLoad = function() {
                        el.setAttribute('data-loaded', true);
                        el.closest('.grid-item').classList.add('content-loaded');
                        // Trigger Masonry layout update
                        masonryInstances.forEach(msnry => msnry.layout());
                    };

                    if (el.complete && el.naturalHeight !== 0) {
                        onImgLoad();
                    } else {
                        el.onload = onImgLoad;
                    }
                }
            });
            observer.observe();

            // Force a layout check after a short delay to ensure Masonry has set up correctly
            setTimeout(() => {
                masonryInstances.forEach(msnry => msnry.layout());
            }, 100);
        });

        function filterGallery(type) {
            // Update buttons
            document.querySelectorAll('.filter-btn').forEach(btn => btn.classList.remove('active'));
            event.target.classList.add('active');

            // Filter sections
            document.querySelectorAll('.gallery-section').forEach(sec => {
                if (type === 'all' || sec.id === 'section-' + type) {
                    sec.style.display = 'block';
                } else {
                    sec.style.display = 'none';
                }
            });
            
            // Trigger Lozad observation on visible elements
            // (Lozad observes viewport, but hiding/showing might affect it)
            // Actually Lozad uses IntersectionObserver so it should handle it.
            
            setTimeout(() => {
                masonryInstances.forEach(msnry => msnry.layout());
            }, 10);
        }
    </script>
</body>
</html>`;

    fs.writeFileSync(path.join(DIST, 'gallery.html'), htmlContent);
    console.log('Created gallery.html in dist');
}

function createDemoHtml() {
    const htmlContent = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Static Random Pic API Demo</title>
    <style>
        body { font-family: sans-serif; max-width: 800px; margin: 20px auto; padding: 20px; }
        .card { border: 1px solid #ccc; padding: 20px; margin-bottom: 20px; border-radius: 8px; }
        img { max-width: 100%; height: auto; border-radius: 4px; display: block; background: #eee; min-height: 200px; }
        .btn { display: inline-block; padding: 10px 20px; background: #007bff; color: white; text-decoration: none; border-radius: 4px; }
        .bg-box { width: 100%; height: 200px; background-size: cover; background-position: center; border-radius: 4px; border: 1px dashed #999; display: flex; align-items: center; justify-content: center; color: white; text-shadow: 0 1px 3px rgba(0,0,0,0.8); font-weight: bold; }
    </style>
</head>
<body>
    <h1>Static Random Pic API (Client-Side)</h1>
    <p>
        This is a static implementation. Images are randomized at build time.
        <a href="https://gallery.acofork.com" class="btn" style="float: right;">View Gallery</a>
    </p>

    <div class="card">
        <h2>Horizontal Image (横屏)</h2>
        <p>Using <code>&lt;img alt="random:h"&gt;</code>:</p>
        <!-- Logic: Script finds alt="random:h" and sets src -->
        <img alt="random:h" title="Random Horizontal Image" />
        <br>
        
        <p>Background Image (<code>data-random-bg="h"</code>):</p>
        <!-- Logic: Script finds data-random-bg="h" and sets style.backgroundImage -->
        <div class="bg-box" data-random-bg="h">
            Background Image
        </div>
    </div>

    <div class="card">
        <h2>Vertical Image (竖屏)</h2>
        <p>Using <code>&lt;img alt="random:v"&gt;</code>:</p>
        <img alt="random:v" style="max-height: 400px;" title="Random Vertical Image" />
    </div>

    <!-- Import the single generated script -->
    <script src="random.js"></script>
</body>
</html>`;
    fs.writeFileSync(path.join(DIST, 'index.html'), htmlContent);
    console.log('Created demo index.html in dist');
}

build();
